apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dealership
  name: dealership
  namespace: sn-labs-siyabongafik
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
      - image: us.icr.io/sn-labs-siyabongafik/dealership:latest
        imagePullPolicy: Always
        name: dealership
        ports:
        - containerPort: 8000
          protocol: TCP
      - image: us.icr.io/sn-labs-siyabongafik/dealer-api:latest
        imagePullPolicy: Always
        name: dealer-api
        ports:
        - containerPort: 3030
          protocol: TCP
      - image: mongo:latest
        imagePullPolicy: Always
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: dealership
  name: dealership
  namespace: sn-labs-siyabongafik
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: dealership
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: dealership
  name: dealer-api
  namespace: sn-labs-siyabongafik
spec:
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 3030
  selector:
    run: dealership
  type: ClusterIP
